[phases.setup]
nixPkgs = ["...", "ffmpeg_6-full"]

[phases.install]
cmds = ["yarn install --frozen-lockfile"]

[phases.build]
cmds = ["yarn build-ts"]

[start]
cmd = "yarn distribute"

[env]
NODE_ENV = "production"